book1 = {'book_id': 10,
         'isbn': 1234,
         'title': 'The book',
         'authors': ['Bob Author', 'Helio Author'],
         'pages': 500,
         'room_id': 2,
         'format': 'Slippery back',
         'publisher': 'Crazy dude publishing',
         'publication_date': '1820 01 02',
         'description': 'a book',
         'thumbnail': 'a thumbnail',
         'loaned': False}

book2 = {'book_id': 20,
         'isbn': 1235,
         'title': 'Great book',
         'authors': ['Jane Author'],
         'pages': 123,
         'room_id': 2,
         'format': 'Sturdy thing',
         'publisher': 'Sane gal publishing',
         'publication_date': '2016 12 31',
         'description': 'Another book',
         'thumbnail': 'another thumbnail',
         'loaned': False}

book3 = {'book_id': 30,
         'isbn': 1236,
         'title': 'Great Songs',
         'authors': ['Jane Author'],
         'pages': 100,
         'room_id': 3,
         'format': 'Sturdy thing',
         'publisher': 'Sane gal publishing',
         'publication_date': '2000 01 01',
         'description':
         'A very nice book about songs! All the best artists',
         'thumbnail': 'another thumbnail',
         'loaned': False}

book4 = {'book_id': 40,
         'isbn': 1237,
         'title': 'Great Poems',
         'authors': ['Jane Author'],
         'pages': 3,
         'room_id': 6,
         'format': 'Sturdy thing',
         'publisher': 'Sane gal publishing',
         'publication_date': '1999 12 31',
         'description':
         'A very nice book about poems! All the best poets',
         'thumbnail': 'another thumbnail',
         'loaned': False}
